### ISSUE TITLE
Tutorial for ELA node client setup?

### ISSUE THREAD

**Issue by mmate91** [elastos/Elastos.ELA.Client#12]
Hi Kevin,
Would it be useful to make a basic tutorial for the setup of ELA node client, and about its functions (create wallet, transactions)? I was thinking of creating a medium blog post.

UPDATE:
as far as i can see, i'll need Elastos.ELA.Utility which hasn't been published yet :)

**Comment by yz89** [comment]
Elastos.ELA.Utility is being refactored and go public soon. This day or two.

**Comment by AlexpanXX** [comment]
I'll write a tutorial later in the day, instruct the commands in the client.

**Comment by kevingzhang** [comment]
Great, please notify me when your tutorial is done @AlexpanXX

**Comment by mmate91** [comment]
I think that's a complete tutorial :+1:  :100:  :)
