### ISSUE TITLE
Send transaction Double spend

### ISSUE THREAD

**Issue by xiaomingfuckeasylife** [elastos/Elastos.ELA.Client#36]
## Problem Definition 
The code comes from the master branch and when I am trying to use ela-cli tool to send a transaction , It always return a double spend transaction .After some code digging , I find out that the input referece transaction id is not reversed .

## Solution
wallet.go
```go
input := &Input{
			Previous: OutPoint{
				TxID:  *reverseBytes(utxo.Op.TxID),
				Index: utxo.Op.Index,
			},
			Sequence: utxo.LockTime,
		}
```
Add a function
```go
func reverseBytes(src Uint256)(*Uint256){
	rst := make([]byte,32)
	for i:= 0 ; i < len(src);i++ {
		rst[i] = src[len(src)-1-i];
	}
	ret , _ := Uint256FromBytes(rst)
	return ret
}
```
@hejianhui

**Comment by hejianhui** [comment]
Have you reproduce this bug?
